# Here you can define various configuration parameters for functions
# such as environment variables, memory size, execution schedule and timeout duration.
# These can be defined on a project, stage or function level. If the same parameter is
# defined on multiple levels the lowest level will take precedence.
# For example, uncommenting the config below will result in
# the function ping having the following configuration:
# memory_size: 512
# timeout: 60
# cron: "* * * * ? *"
# env:
#   KEY: project
#   KEY2: stage
#   KEY3: function

project:
  stages:
    - name: development
      functions:
      - name: signup
        env:
          APP_NAME: App # use any name here, this will only be used to generate the email body
          SOURCE_MAIL: app@example.com # the source address emails will be sent from, use an address that is verified in SES
